### ISSUE TITLE
Order By Field Doesn't Respect required=False

### ISSUE THREAD

**Issue by kevinastone** [alex/django-filter#113]
It attempts to get the default ordering from a choices field (I was using a free form regex field instead).  It should check if its required or there's a default before trying to retrieve the first value in the choices field.

Presumably, without a provided order_by parameter, it should default to the model/queryset's default ordering and not just pick the first listed choice.

https://github.com/alex/django-filter/blob/develop/django_filters/filterset.py#L297

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
