### ISSUE TITLE
Clarify url syntax in documentation

### ISSUE THREAD

**Issue by andybak** [alex/django-filter#131]
New to django-filter and I assumed that this kind of url would be accepted 'out-of-the-box':

?field_name__gte=4

i.e. the same syntax used in the Django Admin.

Unless I'm missing something, it seems that it's not (at least without some extra work on the users side)

It might be worth documenting this as I'm sure I'm not the first person to make this assumption and it would save people digging through the code to see if it's an error on their part

**Comment by k4nar** [comment]
I agree, I struggled a bit yesterday due to lack of documentation, it would be very great :) .

**Comment by carltongibson** [comment]
Whilst I agree the docs as they stand could do with going over, I'm going to close this issue.

The specific case is a long way from what's supported by Django Filter so I'm not sure how I'd action it as an example. 

I will review all issues with the Documentation label as I rework the docs.
