### ISSUE TITLE
MultipleChoiceFilter __init__() takes at least 2 arguments (4 given)

### ISSUE THREAD

**Issue by l0rn** [alex/django-filter#146]
When setting up a filter for a M2M field specifing it directly the exception rises.

    class ProductFilter(django_filters.FilterSet):
        tags__tag_name = django_filters.CharFilter(widget=TagWidget)
        categories = django_filters.ModelMultipleChoiceFilter()

        class Meta:
            model = BasicImage
            fields = ['tags__tag_name', 'categories']

If I comment out the categories field and use the default by just entering it in the meta field list it works just fine.. why is that?

**Comment by skolsuper** [comment]
+1 "ModelMultipleChoiceFilter requires at least a queryset parameter" ought to be documented, I just had a frustrating half hour.

**Comment by carltongibson** [comment]
@skolsuper — Sorry for your pain here. Improving the docs generally is on the TODO list. (PRs welcome!)
