### ISSUE TITLE
Allow easy overriding of Filter.field_class from FilterSet

### ISSUE THREAD

**Issue by melinath** [alex/django-filter#161]
FilterSet can currently override a lot of things about its filters - but it can't override the form field class. This makes it difficult to do things like use django-filter with floppyforms, or more generally to use any custom field that improves UI on your site.

This should be fairly easy to implement - just allow field_class to be passed in on instantiation, and people can use filter_overrides to do the rest.

For full similarity with Django, you could also add support for passing in a choice form field as well as a normal one. See also: model Field.formfield.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
