### ISSUE TITLE
Crash with Django 1.7 and rest_framework on integer+choices fields 

### ISSUE THREAD

**Issue by Karmak23** [alex/django-filter#163]
Hi,

When using django-filter with Django1.7+DRF on  integer fields with choices, I've got a stacktrace like this one:

http://dev.1flow.net/codega-studio/popshake-webdev/group/43540/

When used on primary keys, boolean and simple integer fields (no choices), there is no problem. 

I tried to investigate the code, but didn't see anything obvious. My model/Serializer/Viewset are:

```python
# Model
class Template(models.Model):
    name = models.CharField(max_length=64)
    tempo = models.IntegerField(choices=((90, 90), (100, 100), (110, 110)), default=100)
    duration = models.IntegerField(default=15)
    is_active = models.BooleanField(default=True)

# DRF Serializer
class TemplateSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Template
        fields = ('name', 'tempo', 'duration', 'url', )

# DRF ViewSet
class TemplateViewSet(viewsets.ModelViewSet):
    queryset = models.Template.objects.filter(is_active=True)
    serializer_class = serializers.TemplateSerializer
    filter_fields = ('duration', ) # 'tempo', crashes for now

    def get_queryset(self):
            # workaround crash in django-filter on integer+choices
            queryset = super(TemplateViewSet, self).get_queryset()

            tempo = self.request.QUERY_PARAMS.get('tempo', None)

            if tempo is not None:
                queryset = queryset.filter(tempo=int(tempo))

            return queryset

```

I use `django-filter` in a DRF viewset via `filter_fields` like [told here](http://www.django-rest-framework.org/api-guide/filtering#djangofilterbackend).

regards,

**Comment by carltongibson** [comment]
I'm going to close this — for one the link to the Sentry page has disappeared. 

If anyone can provide a PR showing the issue I'm happy to look at it.

**Comment by Karmak23** [comment]
That's fine. The sentry page dissapeared because of beiing too old and cleaned for that.
In fact, re-reading [your comment](https://github.com/alex/django-filter/issues/163#issuecomment-57161920) with enough attention, you gave me the answer: the tempo choices are created via a generator, but I didn't notice that in the first place, because it was called as a function which I thought returned a tuple. My bad. 

I will enclose it with `tuple()` and it should get rid of the problem.
Thanks a lot,
