### ISSUE TITLE
Making both ascending and descending ordering default option

### ISSUE THREAD

**Issue by livenson** [alex/django-filter#178]
Currently to allow ordering results in ascending and descending order one must explicitly add names twice:

```python
class Meta(object):
        model = models.MyModel
        fields = [
            'name',
        ]
        order_by = [
            'name',
            '-name',
        ]
```

Now it doesn't feel right - asc/desc sorting (almost) always comes in pairs. What would you think about modifying default behaviour by offering those sorting directions at once?

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
