### ISSUE TITLE
BooleanFilter allows '2' and '3' values

### ISSUE THREAD

**Issue by qrilka** [alex/django-filter#187]
NullBooleanSelect allows it and I suppose that it should not be allowed.

**Comment by chaoslawful** [comment]
Yes, that's very annoying. `BooleanFilter` used Django's `NullBooleanField` whose widget `NullBooleanSelect` corresponds 1/2/3 to None/True/False. So only literal True/False works for a `BooleanFilter` but not 1/0 as its comments said. Wish it be fixed soon.

**Comment by carltongibson** [comment]
OK, I'm going to close this. 

The [docs say that the BooleanFilter matches `True` and `False`](https://django-filter.readthedocs.org/en/latest/ref/filters.html#booleanfilter) which is correct.

If you want additional/different logic for matching query parameters you need to create a custom widget and use that. Subclassing `django.forms.widgets.NullBooleanSelect` seems like the way to go. 

You'd need to override `value_from_datadict` to match the values you want in the manner you want. The implementation there is fairly straight-forward:

```
    def value_from_datadict(self, data, files, name):
        value = data.get(name, None)
        return {'2': True,
                True: True,
                'True': True,
                '3': False,
                'False': False,
                False: False}.get(value, None)
```

... adjust the map for the behaviour you require. 

I don't really see this as being in scope for Django-Filter; it's pretty easy to create your own widgets and if the behaviour of `NullBooleanSelect` is _wrong_ then that's a Django issue, which should be taken up there.

If somebody comes up with a tested, documented pull request for a custom widget that covers all the bases I'm happy to consider it for Django Filter at that time.

**Comment by rpkilby** [comment]
Btw, #378 should fix this (allows all capitalizations of true/false, as well as mapping 1: true, 0: false)
