### ISSUE TITLE
Add support for ISO 8601 format dates/datetimes

### ISSUE THREAD

**Issue by carltongibson** [alex/django-filter#189]
See [Filtering on Date Fields With `DjangoFilterBackend` Doesn't Quite Work. · Issue #1338 · tomchristie/django-rest-framework](https://github.com/tomchristie/django-rest-framework/issues/1338) over on DRF. 

It [looks like there's no fix coming in Django soon](https://code.djangoproject.com/ticket/23448) so we should add something here. 

:loudspeaker: @copitux — sorry for the interruption — Would we be able to incorporate your code from [Iso 8601 DateTimeFilter to Django Rest Framework and Django-Filter](https://gist.github.com/copitux/5773821)? (It doesn't provide licence info.)

**Comment by alexbw** [comment]
+1, this coming in anytime soon?

**Comment by thedrow** [comment]
Actually I found out that using either Arrow or Delorean for parsing the dates is way better then adding support for a specific format.
I'd be willing to provide form fields that parses dates with those libraries.
The form fields won't introduce hard dependencies but will allow the client to filter with any format that Arrow or Delorean are familiar with.

**Comment by carltongibson** [comment]
Hi @thedrow. 

This sounds great. What would it look like from the declaration point of view, and would it cover all the cases?

I'm happy to recommend a dependency if the benefit is there...

**Comment by thedrow** [comment]
I have no idea actually. Maybe we should consider introducing a datetime_parser keyword argument that will determine the form field's datetime parser.

**Comment by citizen-stig** [comment]
+1, it will be really good feature, especially when using django_filter with djangorestframework

**Comment by thedrow** [comment]
We're using Delorean and this currently works for us:
```python
class DeloreanDateTimeField(forms.DateTimeField):
    def strptime(self, value, format):
        return delorean.parse(value, dayfirst=False).datetime

class DeloreanDateTimeFilter(DateTimeFilter):
    field_class = DeloreanDateTimeField
```
We could instead override the default Django Date/Time form field to accept a parser callable and call it in ```strptime()```. This will also require us to add a new keyword argument to all Date/Time related filters.

**Comment by carltongibson** [comment]
Hey @thedrow — at this point I'm inclined to finish and merge #264 rather than add a dependency.
