### ISSUE TITLE
ModelMultipleChoiceFilter.filter retrieve a QuerySet, not the value from request.

### ISSUE THREAD

**Issue by BrickXu** [alex/django-filter#200]
I want to use ```ModelMultipleChoiceFilter``` to validate the name, whether exist or not. And do some filtering on the queryset.

```Python
class ComponentFilter(FilterSet):
    name = ModelMultipleChoiceFilter(queryset=Component.objects.all(),
                                     name='name',
                                     to_field_name='name')
    class Meta:
        model = Component
        fields = ('name', 'dist_git_path')
```

And I found ```ModelMultipleChoiceFilter.filter``` always retrieve a QuerySet instead of the value of name, and ```filter``` will not work well.

```Python
def filter(self, qs, value):
        # value is a queryset here!
        value = value or ()
        if len(value) == len(self.field.choices):
            return qs
        q = Q()
        for v in value:
            # it does not work with a queryset!
            q |= Q(**{self.name: v})
        return qs.filter(q).distinct()
```

Is it a bug for ModelMultipleChoiceFilter ?

**Comment by carltongibson** [comment]
Hi @BrickXu — `ModelMultipleChoiceFilter` is for a ForeignKey — selecting multiple related items. To select an attribute use `MultipleChoiceFilter` instead.
