### ISSUE TITLE
Cannot use both .filter and .exclude with MethodFilter

### ISSUE THREAD

**Issue by angrybakon** [alex/django-filter#208]
I am not sure whether or not the issue is coming from django-filter.

I added a MethodFilter in my FilterSet:

```python
is_foo = django_filters.MethodFilter(action='check_is_foo')

def check_is_foo(self, queryset, value):
    if value:
        return queryset.filter(model__name__iexact='foo')
    return queryset.exclude(model__name__iexact='foo')
```

If request sends `is_foo=True` I want the queryset to use `.filter`, if not use `.exclude`.

But the former is always used instead. I've tried to print stuff in Django's code to make sure.

However if I comment out the 2 first lines of `check_is_foo`, my results are correctly filtered (using `.exclude`).

Using Django 1.6.2.

**Comment by carltongibson** [comment]
Hmmm. I'd guess `value` is always evaluating to True. Can you put a breakpoint in or log `value` to check you're getting the value (and type) that you're expecting?

**Comment by angrybakon** [comment]
I'm so sorry I didn't update the issue yesterday.

Must have been brainfarting... But when I tried again to check with some
'print value' I noticed it was a string.

Converting it to a boolean did the thing.

**Comment by carltongibson** [comment]
Excellent.
