### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by tricoder42** [alex/django-filter#209]
Django 1.8 `replaces django.db.models.related.RelatedObject`  with `django.db.models.fields.related.ForeignObjectRel`. 

https://docs.djangoproject.com/en/1.8/releases/1.8/#model-field-related

`RelatedObject` is used in `django_filter/filterset.py`. However, even when I fix the import and usage, tests related to relations remains broken.

**Comment by carltongibson** [comment]
Thanks for this. 

>  However, even when I fix the import and usage, tests related to relations remains broken.

#210 is passing. What's the failing you mean?

**Comment by tricoder42** [comment]
I managed to fixed it after all and sent the pull request. The problem was this line:

```
queryset = f.model._default_manager.all()
```

see the PR diff for more info.

**Comment by carltongibson** [comment]
OK, cool, thanks. I'll review later. Awesome!
