### ISSUE TITLE
How to change the Widget to an autocomplete?

### ISSUE THREAD

**Issue by aidanlister** [alex/django-filter#211]
I've looked through the docs and the source code and I can't work out how I might be able to use an autocomplete widget (e.g. django-autocomplete) to filter by. Is it possible?

**Comment by wofl** [comment]
I'm successfully using django-filter together with [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light).
It's as simple as:

```python
class FilterWithAutocomplete(django_filters.FilterSet):
    any_field = django_filters.ModelChoiceFilter(queryset=MyModel.objects.all(),
                        widget=autocomplete_light.ChoiceWidget('AutocompleteName'))
    class Meta:
        model = MyModel
        fields = ['any_field']
```

**Comment by rujun-dai** [comment]
Hi, I am wondering how you used autocomplete_light. I just used pip install django-autocomplete-light to install, but I can not put 'autocomplete_light' in setting.py, it seems like 'autocomplete_light' does not exist. @wofl

**Comment by rpkilby** [comment]
Hi @rujun-dai - this question is over two years old, and DAL has gone from version 2.0.7 to 3.2.9 during this time. I'd recommend reading the current [docs](https://django-autocomplete-light.readthedocs.io/en/master/install.html) for DAL, as the API has likely changed.

**Comment by Lifechess** [comment]
can you give an example with ModelSelect2

**Comment by Real-Gecko** [comment]
> can you give an example with ModelSelect2

```python
import django_filters as filters
from dal_select2.widgets import ModelSelect2
from dictionaries.models import RouteStatus

from .models import Route


class RouteFilter(filters.FilterSet):
    status = filters.ModelChoiceFilter(
        queryset=RouteStatus.objects.all(),
        widget=ModelSelect2(reverse_lazy('dictionaries:auto', args=['route_status'])),
    )

    class Meta:
        model = Route
        exclude = ('id')
```
`'dictionaries:auto'` with `args=['route_status']` is an autocomplete view from another app that is usual subclass of `Select2QuerySetView` from `dal_select2.views`.

IMO this has to be added to documentation as it is done in [django-tables2 documentation](https://django-tables2.readthedocs.io/en/latest/pages/filtering.html)
