### ISSUE TITLE
how to filter against datetime

### ISSUE THREAD

**Issue by learner010** [alex/django-filter#212]
I am trying to filter contents against date time. I have following filter set.

`start_date = django_filters.DateTimeFilter(name = "date_time", lookup_type = 'contains')`

I get following error for the url, `report/?start_date=2015-01-16`
```
Incorrect datetime value: '%2015-01-16 00:00:00+05:45%' for column 'date_time' at row 1
```

What is the correct way to set datetime filter?

**Comment by sheepeatingtaz** [comment]
I have been having the same problem today, and I have implemented this solution:

https://groups.google.com/d/msg/django-filter/lbi_B4zYq4M/37s63u0WrncJ

I will look to see if I can add a pull request to add it into the main code, but I'm quite new to django and github, so don't hold your breath!

**Comment by frlinw** [comment]
Similar issue here.

It would be really nice to be able to filter a DateTimeField with "contains" or "startswith" or "year, month, day". Sometimes you just want to find an exact date but not an exact time... (but if a better way exist, I would be glad to know it, I'm quite new in django universe)

In addition, the filter isnull can be useful in some cases.
invoices/?payer__last_name=sweet&payment_date__isnull=True -> Damn 3 invoices unpaid, Hey M. Sweet, where is my money ?

**Comment by frlinw** [comment]
Ok, if you need a particular date on DateTimeField, you can use a range.
mydate__gte=2015-03-03 00:00:00&mydate__lt=2015-03-04 00:00:00
It's not really beautiful but it works.

I haven't found solutions for isnull

**Comment by rvernica** [comment]
I can confirm that `contains` does not seem to work on `DateTime` even if it works on Django ORM. 

So, after setting up `django-filter` with Django REST framework:
```
    filter_fields = {
        'visit_date': ['gte', 'lt', 'contains'],   
    }
```
This URL works `visits/?visit_date__gte=2015-05-27&visit_date__lt=2015-05-28`

while this URL *does not* work `visits/?visit_date__contains=2015-05-27` (returns empty set).

`contains` works in Django ORM:
```
>>> Visit.objects.get(visit_date__contains='2015-05-27')
...
MultipleObjectsReturned: get() returned more than one Visit -- it returned 2!
```

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.

**Comment by harshacheemakurt** [comment]
for a DateFilter we are still not able to filter just by passing year
