### ISSUE TITLE
Filtering for None values

### ISSUE THREAD

**Issue by akrf** [alex/django-filter#214]
Is there a way to filter for fields that have no value? I have a model with an optional ForeignKey and I would like to use django-filter to allow users to generate a list of objects without any value in that ForeignKey, ie `MyObject.objects.filter(myfkfield=None)`. I didn't see anything about this in the Filter Reference docs.

Thanks!

**Comment by wofl** [comment]
You could always subclass ```django-filters.Filter``` and overwrite ```def filter(self, qs, value):``` to create your own filters.
Take a look at [filters.py](https://github.com/alex/django-filter/blob/develop/django_filters/filters.py)!

**Comment by carltongibson** [comment]
I'm marking this and #211 for "Documentation". 

Subclassing `Filter` is pretty easy — and there are lots of examples to provide a base reference cf #196, #198 — so I want to encourage users to go that way.

**Comment by akrf** [comment]
Thank you for the pointers. I came up with this:

```
class NoneFilter(django_filters.Filter):
    field_class = forms.BooleanField

    def filter(self, qs, value):
        if not value:
            return qs.exclude(**{self.name: None})
        return qs
```

This does what I want it to do, however to make the interface make sense I am using it like this:

    myfkfield = NoneFilter(label='Has myfkfield value')

Where in the filter should I set the default label so that I don't have to do it everytime I use `NoneFilter`? I want it to be something like `'Has %s value' % self.name`.

**Comment by carltongibson** [comment]
Related to #45 etc

**Comment by carltongibson** [comment]
Closing this in favour of #261
