### ISSUE TITLE
Foreign key filtering by pk doesn't work

### ISSUE THREAD

**Issue by scott113341** [alex/django-filter#216]
Hello, I'm using django-filter with Django Rest Framework (DRF) and came across a bug related to `pk` vs `id` when filtering across foreign keys.  

For example, I have the following DRF ViewSet (the filter backend is already included via `DEFAULT_FILTER_BACKENDS`): 
```
class ChildViewSet(viewsets.ReadWriteDestroyFlatViewSet):
    queryset = models.Child.objects.all()
    lookup_field = 'pk'
    serializer_class = serializers.ChildSerializer

    filter_fields = ('parent__pk',)
```

This raises the following error:
```
TypeError at /api/v1/children
Meta.fields contains a field that isn't defined on this FilterSet
Request Method:	GET
Request URL:	http://127.0.0.1:8000/api/v1/children?parent__pk=1
Django Version:	1.7.4
Exception Type:	TypeError
Exception Value:	
Meta.fields contains a field that isn't defined on this FilterSet
Exception Location:	/Users/schardy/VirtualEnvs/iris/lib/python2.7/site-packages/django_filters/filterset.py in __new__, line 172
...
```

However, changing the `filter_fields` property to `('parent__id',)` works fine and lets me filter by the parent's id by navigating to `http://127.0.0.1:8000/api/v1/children?parent__id=1`.  

I did my best to track down this bug, which I believe originates inside [`django.db.models.options`](https://github.com/django/django/blob/b626c289ccf9cc487f97d91c2a45cac096d9d0c7/django/db/models/options.py#L438), which sets up an internal cache called `_name_map` that contains key-value pairings of the internal field name -> field objects.  This cache does NOT include a key-value pair for `pk`, but it does for `id`.  

Adding the following code after line 451 makes filtering by `pk` work properly because it adds a key-value pair for the `pk` field:
```
if f.name == 'id':
    cache['pk'] = (f, model, True, False)
```

I'm not at all confident this is the right solution, which is why I'm opening this issue here.  Apologies for the incomplete examination of the problem, but I'm afraid I've reached the limit of my bug-hunting abilities.  Thank you, and any thoughts?

**Comment by carltongibson** [comment]
Hey @scott113341 — Nice. :-)

Thanks for the report. I need to have a think about it before I can say anything sensible.

**Comment by scott113341** [comment]
Development:

Turns out that this works fine when simply navigating to `http://127.0.0.1:8000/api/v1/children?parent=1`

I can't believe I didn't try this before!  It's still a valid bug in my opinion because it goes against the expected behavior of `pk`, BUT throwing this behavior in the docs would probably be sufficient too.  

NOTE: only confirmed as working with models that have numeric primary keys (aka the `id` field is the primary key on the model)

**Comment by carltongibson** [comment]
Hey @scott113341 — Thanks for the follow up. 

I'm not sure what to say on the bug/not bug point right now.  

First off, I'm glad you solved it. Second, any pull requests on the docs will be **very warmly** received. (There's a few code-type issues/PRs open that I'll get to first but "Docs" is basically "Top of my list")

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider pull requests here. We may have capacity to reconsider in the future.
