### ISSUE TITLE
Default ordering should be clarified

### ISSUE THREAD

**Issue by JocelynDelalande** [alex/django-filter#228]
Default ordering is not documented, however, it happens to be just the first item of ordering fields list. As coded at https://github.com/alex/django-filter/blob/develop/django_filters/filterset.py#L373

IMHO, you need either :
- don't touch ordering if ordering field is unbound
- document the fact it's using the first field and provide a way to override the default ordering field

**Comment by carltongibson** [comment]
I'm going to close this, since the way ordering works, and the documentation for it, will change with #204. I will review this after that's finished.
