### ISSUE TITLE
Supply parameters to filterset

### ISSUE THREAD

**Issue by durdenk** [alex/django-filter#231]
having successfully used filtersets, wonder how can ı supply model name and fields etc to filterset wihtout writing hardcoded, If I can subclass and give some parameters. Anyone has a gist?

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions. 

See here: https://github.com/alex/django-filter/blob/develop/django_filters/filterset.py#L484
