### ISSUE TITLE
try rename field as model form, but failed

### ISSUE THREAD

**Issue by mingissb** [alex/django-filter#232]
Hello,
I try to modify the label just like the way I change the label in modelform.
here are the codes:

```
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _ 
import django_filters
from .models import IssueReportInfo

# Create the form class.
class IssueReportInfoFilter(django_filters.FilterSet):
    class Meta:
        model = IssueReportInfo
        fields = ['sort', 'issue_status',]
        order_by = ['startdate',]
        labels = {
            'sort': _('问题分类'),
            'issue_status': _('问题状态'),
            'startdate': _('发生时间'),
        }
```

But the showing labels didn't change.
Did I make a wrong way/
Or what should I do?
Thank you in advance.

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!

**Comment by mingissb** [comment]
Hello Gibson,

Thank you for concern my issue.

I have already forward it to mailing list.

Could you help me.

Thank you.
