### ISSUE TITLE
Need empty result list on filter initialization

### ISSUE THREAD

**Issue by yn-coder** [alex/django-filter#237]
When user opens the page with filter, they see the empty form and full list of results.

I need to not to display the result until user press Search for a first time.

![2015-05-13 13_18_07-basic fuel template _ naiveshark](https://cloud.githubusercontent.com/assets/8451944/7608527/15dbcaaa-f973-11e4-8f75-6908fcd94169.png)

**Comment by yn-coder** [comment]
I've post the same question here http://stackoverflow.com/questions/30211058/empty-result-list-on-django-filter-page-startup

**Comment by yn-coder** [comment]
After some studies, I've found this simple solution

```` python

class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product
        fields = [ 'shortname', 'fullname', 'description', 'product_type',   ]
        
    def __init__(self, *args, **kwargs):
        super(ProductFilter, self).__init__(*args, **kwargs)

        # at sturtup user doen't push Submit button, and QueryDict (in data) is empty
        if self.data == {}:
            self.queryset = self.queryset.none()

```

I think, this solution is stable. How do you think?

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!
