### ISSUE TITLE
How to generate the list of RangeFilter's from ModelMultipleChoiceFilter?

### ISSUE THREAD

**Issue by yn-coder** [alex/django-filter#239]
How to generate the list of RangeFilter's from ModelMultipleChoiceFilter?

ModelMultipleChoiceFilter produce the list of variants to choose. Filter will check - ``are property exist in instance?`` I need to generate the list of RangeFilter widgets, to check values, linked to ManyToManyField.

Can you give me an example?

**Comment by yn-coder** [comment]
Here is a scetch for DB struct and wanted interface 

![generate the list of rangefilter](https://cloud.githubusercontent.com/assets/8451944/7649066/13a518ce-faf2-11e4-99d6-d131d60b9d98.gif)

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!
