### ISSUE TITLE
How to set initial data for django-filters?

### ISSUE THREAD

**Issue by Winnerer** [alex/django-filter#242]
Is there a way to set initial data for fields?

**Comment by Winnerer** [comment]
I got it.
The problem was I could not set initial for RangeFilter. According to widgets.py I realized, that it gets initial values like ```return [value.start, value.stop]```. Why not dict?

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!
