### ISSUE TITLE
How can I set up the queryset depend on some request parameters?

### ISSUE THREAD

**Issue by yn-coder** [alex/django-filter#244]
I have class ```SomeListView(FilterMixin, django_filters.views.FilterView)```

How can I set up the queryset depend on some request parameters? 

Something like

```self.filterset_class = ProductFilterSet( self.request.GET , queryset=Model.objects.filter( field = request['param_name'] ) )```

**Comment by bashu** [comment]
I think this one is solved already

**Comment by carltongibson** [comment]
Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. Thanks!

**Comment by yn-coder** [comment]
I've got the ansers here
https://github.com/bashu/django-filters-mixin/issues/3
and here #245
