### ISSUE TITLE
Cannot define order when defining filter fields in a dictionary

### ISSUE THREAD

**Issue by wimfeijen** [alex/django-filter#250]
Hi, 

When defining filters in a dictionary as in the following example, we loose the ability to define the order of fields. Maybe it is better to use an ordered dictionary instead, or a list of lists (tuple of tuples)?

        fields = {'price': ['lt', 'gt'],
                  'release_date': ['exact'],
                 }

Example taken from: http://django-filter.readthedocs.org/en/latest/usage.html#the-filter

**Comment by carltongibson** [comment]
Yeah. The dictionary syntax is a convenience here — most useful for quickly putting together FilterSets, and inspired from tie-in usage when creating APIs (where order isn't important) with Django Rest Framework. 

If order is important to you, drop back to defining the filter attributes individually and provide `fields` as a list. 

(Of course I'm open to a Pull Request that handles using an OrderedDict but it's not something I'm going to work on per se.)

**Comment by dmarcelino** [comment]
I've also stumbled upon this issue and the following seems to work for me:

```
        fields = OrderedDict([
            ('subtype', ['exact']),
            ('price', ['lt', 'gt']),
            ('description', ['icontains',]),
            ('created_at', ['year__gt'])
        ])
```

@carltongibson, I understand this is not exactly guaranteed behaviour since it's not supported but do you think it's likely to break at some point?
