### ISSUE TITLE
AutoField not excluded in filter?

### ISSUE THREAD

**Issue by s2krish** [alex/django-filter#254]
This is more of question. I wonder why AutoField is excluded filter list when fields is set to None on filter class.

Specifically talking about code snippet in filters.filters_for_model

    fields = [f.name for f in sorted(opts.fields + opts.many_to_many)
            if not isinstance(f, models.AutoField)]

Thanks in advance!

**Comment by carltongibson** [comment]
Just a design decision I guess.
