### ISSUE TITLE
Meta class option form has no influence

### ISSUE THREAD

**Issue by jlec** [alex/django-filter#256]
Following this

https://django-filter.readthedocs.org/en/latest/usage.html#custom-forms-using-form

it should be possible to add a custom Form(), but no matter what I specify I always get the whole Modelform. Same when I do not specify any, but only set fields. I would expect to become a Form only specifying what I set there, but I get the whole ModelForm.

**Comment by jlec** [comment]
It's invalid. Wrong usage of the View. Sorry for the noice.

**Comment by carltongibson** [comment]
Glad you fixed it. 👍
