### ISSUE TITLE
lookup_type list not working when defined explicitly in Filter constructor?

### ISSUE THREAD

**Issue by t1m0thy** [alex/django-filter#265]
Hi.  

I am using django-filters with django-rest-framwork.  I am seeing something unexpected when I use lists of lookup options in the constructor of a Filter.

This works as expected (ignoring that there is no need to define the filter explicitly since it's all defaults) I can query with `?name=test` or `?name__contains=t` etc.   

    class CandidateFilter(django_filters.FilterSet):
        name = django_filters.CharFilter(name="name")
        class Meta:
            model = Candidate
            fields = {"name": ['exact', 'contains', 'in', 'startswith']}

However, this doesn't work:

    class CandidateFilter(django_filters.FilterSet):
        name = django_filters.CharFilter(name="name", lookup_type= ['exact', 'contains', 'in', 'startswith'])
        class Meta:
            model =Candidate
            fields = ["name"]

I've only been able to define a list of lookups using the first version.

Also, using the lookup_type in the constructor when it's not a list also works:

    class CandidateSetFilter(django_filters.FilterSet):
        name = django_filters.CharFilter(name="name", lookup_type="contains")
        class Meta:
             model = CandidateSet
             fields = ["name"]

as expected, such that `?name=test` will look for any name that contains `test` 

I tried to find the right way to write a failing test for this, but I was unsuccessful in finding where to test when the FilterSet uses the dictionary sugar versus explicit definition.  If it's helpful, I would be happy to dig in more with some guidance.

**Comment by carltongibson** [comment]
The `fields` dictionary syntax creates **multiple filters**, one for each lookup type; it does not create a single filter with multiple lookup types. 

If you need multiple lookup types and need to declare them yourself then you need to do it one per line. 

#220 is related. 

I'll close this for now, marking as Documentation, and will review when updating the docs.

**Comment by t1m0thy** [comment]
Awesome, thank you.  I think what confused me was the [lookup_type docs](https://django-filter.readthedocs.org/en/latest/ref/filters.html#lookup-type) in the Filter Reference

>  You can also provide either None or a list or a tuple. If None is provided, then the user can select the lookup type from all the ones available in the Django ORM. If a list or tuple is provided, then the user can select from those options.

**Comment by carltongibson** [comment]
Yes. That certainly implies that the multiple filters should be built. [But they're not](https://github.com/alex/django-filter/blob/develop/django_filters/filterset.py#L142)

I'll reopen this and make sure I have a look at it. (Meta-programming is all very well and good...) Thanks for the report.

**Comment by EricCline** [comment]
Can you provide a little context on the decision to create `forms.MultiValueField`s when somebody passes a list for `lookup_type`?  To me the behavior is different enough from what's expected (multiple filters created) that it feels like a bug.  I can take a crack at a fix if my gut is correct.

**Comment by carltongibson** [comment]
OK. Having reviewed, it's just that we're holding it wrong...

You need to provide the query string like this: `?qty=1&qty_loookup_type=gte` — that's the `MultiValueField` in action. 

Review the discussion and links on #220 — this needs clearing up in the docs but it should all work.

**Comment by EricCline** [comment]
Thanks for the clarification.  I played around with this and was able to get it to work.  Just to note though, the query string syntax is `?qty_0=1&qty_1=gte` as you need to index the fields in the `MultiValueField`.

In my particular case, I'm using the `IsoDateTimeFilter` with `gte` and `lte` and I much prefer the standard django ORM syntax(`qty__gte=1`) so I'm going to use the dictionary syntax with `fields` along with an override to get the multiple filters I'm interested in:

```
class MyFilter(django_filters.FilterSet):

    filter_overrides = {
        models.DateTimeField: {
            'filter_class': django_filters.IsoDateTimeFilter
        }
    }

    class Meta:
        model = models.MyModel
        fields = {
                'created_at': ['gte', 'lte']
        }
```

**Comment by carltongibson** [comment]
@EricCline OK. Fair enough. 

If you want the `qty__gte=1` style and need to declare filters explicitly just declare one per lookup type with the appropriate names (and `name` attribute). 

That there are two styles here is an accident of history. It might be something that would be nice to unify down the road.
