### ISSUE TITLE
Handle JavaScript true/false

### ISSUE THREAD

**Issue by scott-w** [alex/django-filter#268]
If I'm filtering from AJAX, I'm likely to use JavaScript's `true`/`false` values. These will be converted to the strings `"true"` or `"false"` and be ignored by the filter. I would then have to either handle this in JavaScript by using the `"True"` or `"False"` strings, exposing server implementation details, or handle this on the server. I think django-filter should handle this conversion implicitly.

I'm using version 0.10.0

**Comment by carltongibson** [comment]
If you need to support custom values in the query string you need to create a custom widget and implement `value_from_datadict` to handle the values you're after.

**Comment by scott-w** [comment]
I fully appreciate your reasoning, however Javascript is a really common way to interact with a service. Not supporting it in django-filter simply forces everyone to reimplement the exact same functionality.

I'm happy to implement it in your way, however I do think it should be part of the core library.

**Comment by carltongibson** [comment]
> I'm happy to implement it in your way, however I do think it should be part of the core library.

A PR with a widget implementing this, together with tests, and docs including a usage example — users need to pass the `widget` kwarg to the Filter — would be great.

**Comment by scott-w** [comment]
Awesome, cheers.
