### ISSUE TITLE
Case-insensitive ordering

### ISSUE THREAD

**Issue by aronysidoro** [alex/django-filter#272]
Is there functionality for `case-insensitve ordering`?  In the [documentation](http://www.django-rest-framework.org/api-guide/filtering/#searchfilter) it says there is for `SearchFilter`, but it doesn't say anything for ordering?

I have been testing `django-filter` and the default for `ordering` is `case-sensitive`.  

Can `case-insensitive` be easily added somehow?

Thank you

**Comment by carltongibson** [comment]
Ok, first off Django Filter isn't the same as Django Rest Framework – SearchFilter is part of DRF.

As for Django filter, ordering just maps to what you can do with the Django ORM, so the basic answer is "Not Really" — it ultimately comes down to you DBs collation on the named field. 

Sorry

**Comment by aronysidoro** [comment]
Ok, thank you @carltongibson.  Yea, all my googling' so far has led to give me the same answer as you just said.  Thanks for your help!

**Comment by aronysidoro** [comment]
@carltongibson I was able to do `case-insensitive` ordering queries in Django's ORM.  Here's where I posted the code if you are interested.

http://stackoverflow.com/a/31866445/1913888

Thanks

**Comment by carltongibson** [comment]
@aronysidoro Thanks for the follow-up. Nice to see it **can** be done with the ORM.

**Comment by georgkrause** [comment]
@carltongibson Considering there are solutions now, would you mind me to add this as a MR? I am going to implement it anyways, but adding it to django-filter is probably more useful. Let me know!

**Comment by georgkrause** [comment]
@carltongibson I briefly checked the code and I am not sure if I get this right, but if you think this is a better approach I am all in!

**Comment by Ahmed1813** [comment]
Yes, you can achieve case-insensitive ordering by creating a custom ordering class. Instead of using filters.Ordering, you can create a custom class that inherits from filters.Ordering and overrides the get_ordering_value method. Here is an example:
`
from django.db.models.functions import Lower
from django_filters import filters

class CustomOrderingFilter(filters.OrderingFilter):

    def get_ordering_value(self, param):
        descending = param.startswith("-")
        param = param[1:] if descending else param
        field_name = self.param_map.get(param, param)

        return Lower(field_name).desc() if descending else Lower(field_name)
`

You can then use this custom class in place of filters.Ordering to enable case-insensitive ordering.
