### ISSUE TITLE
Improve error message when passing string instead of an iterable in Meta.fields

### ISSUE THREAD

**Issue by rasca** [alex/django-filter#281]
In my code I only have to filter by one field, and I mistakenly wrote:

```
class Meta:
    model = MyModel
    fields = ('my_field')
```

Notice the lack of an ending comma in `fields`. The error was `TypeError: Meta.fields contains a field that isn't defined on this FilterSet`. We could improve this error on the likes: `TypeError: Meta.fields must be an iterable`.

**Comment by carltongibson** [comment]
Yep. No problem. Happy to see a pull request for that.

**Comment by carltongibson** [comment]
Pending a PR, I'm going to close this.
