### ISSUE TITLE
`in` lookup type should use (Typed/Model)ChoiceField by default

### ISSUE THREAD

**Issue by jualvarez** [alex/django-filter#284]
The `in` lookup in django expects an iterable as described in [the docs](https://docs.djangoproject.com/en/1.8/ref/models/querysets/#in). However, in DjangoFilter default behaviour, if a list is passed as query params to a filter with an `in` lookup, they still use the default model field's filter, which raises an exception when the lookup is evaluated.

If you agree with this, I can prepare a PR, but being still a little unfamiliar with the code, I'm not sure where would be the best place to include this logic. It seems to me that the `filter_for_field` method is the best candidate. Then some defaults should be included in each field for the `coerce` attribute.

Your thoughts?

**Comment by carltongibson** [comment]
Not sure. 

I'm not sure what a nice solution would look like here. I'm inclined to think users can specify what they need manually. 

I'm going to close this as it's not something I can work on right now — but I'd be happy to consider a documented, tested pull request if that's something you want to take on!
