### ISSUE TITLE
Feature: multiple field sources

### ISSUE THREAD

**Issue by eldamir** [alex/django-filter#288]
I have a use case with DjangoRestFramework, where I want to search multiple fields from one entry.

I have a form on the website, where I fill in contact details. The fields is send through API call on `http://bla.com/api/customer?contact_search=bob`

Now, If I just wanted to filter where one specific field contains "bob", it would be easy, but my contact names are split into first- middle- and lastnames. I did this to make it work:

Custom filter:

```python
class MultipleSourcesCharFilter(django_filters.CharFilter):
    def filter(self, qs, value):
        if isinstance(value, Lookup):
            lookup = six.text_type(value.lookup_type)
            value = value.value
        else:
            lookup = self.lookup_type
        if value in ([], (), {}, None, ''):
            return qs
        method = qs.exclude if self.exclude else qs.filter

        # self.name is now a list of fields. queue them up like Q(...) | Q(...) | Q(...)
        queries = [{'%s__%s' % (name, lookup): value} for name in self.name]
        queries = functools.reduce(lambda x, y: x | y, [Q(**query) for query in queries])
        qs = method(queries)
        if self.distinct:
            qs = qs.distinct()
        return qs
```

Implementation:

```python
class CustomerFilterSet(django_filters.FilterSet):
    contact_search = MultipleSourcesCharFilter(name=[
        "contacts__first_name",
        "contacts__middle_name",
        "contacts__last_name",
    ], lookup_type='icontains')

    class Meta:
        model = models.Customer
```

I don't know if this is something that should be included by default in the library, but here is a simple way to do it. Maybe `django_filters.Filter` could accept either `name` or `names` and handle it internally?

**Comment by carltongibson** [comment]
This sort of thing is exactly where `MethodFilter` comes in handy.

**Comment by eldamir** [comment]
I'll give it a look

**Comment by eldamir** [comment]
Works great. Thanks

**Comment by carltongibson** [comment]
@eldamir Good. :-)

**Comment by markogw** [comment]
@eldamir 

I would be very happy if you post your solution as code.

Thank you very much.

**Comment by eldamir** [comment]
Sorry @markogw, it is now more than half a decade ago. I have no clue what I did back then. But I guess look into the MethodFilter class in django-filter documentation, and that should put you on the path 😉

**Comment by markogw** [comment]
@eldamir
I see :-) I have found https://stackoverflow.com/questions/57270470/django-filter-how-to-make-multiple-fields-search-with-django-filter and it solved my problem.
