### ISSUE TITLE
Add UUID filter

### ISSUE THREAD

**Issue by thenewguy** [alex/django-filter#294]
For proper handling of filters spanning tables using uuid pks I needed the following:
```
class UUIDFilter(django_filters.Filter):
    field_class = forms.UUIDField
```

Since `field_class` can't be passed to the Filter constructor and UUIDField was added in 1.8 it would be beneficial for this to be available.  Not sure the best course for older djangos that don't have the UUIDField so I am just raising the issue in case it should be tackled.

**Comment by carltongibson** [comment]
This is a covered by #243 (so I'm going to close this). I'd accept a pull request here.
