### ISSUE TITLE
RangeWidget Bug

### ISSUE THREAD

**Issue by ron8mcr** [alex/django-filter#306]
For example, I want to create simple date filter with HTML5 ```<input type="date"...```:
```
created = django_filters.DateFromToRangeFilter(label="Date range",
        widget=RangeWidget(attrs={'type': 'date'}))
```
And that's have to be OK (https://github.com/alex/django-filter/blob/develop/django_filters/widgets.py#L82):
```
class RangeWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (forms.TextInput(attrs=attrs), forms.TextInput(attrs=attrs))
        super(RangeWidget, self).__init__(widgets, attrs)
```
But django's ```forms.widgets.TextInput.__init__``` modificates attrs !(https://github.com/django/django/blob/master/django/forms/widgets.py#L271)
```
    def __init__(self, attrs=None):
        if attrs is not None:
            self.input_type = attrs.pop('type', self.input_type) # dict attrs CHANGED!
        super(TextInput, self).__init__(attrs)
```
So, the first widget would be ```type="date"```, and second still will be ```type="text"```.
The solution is to make a copy of ```attrs```:
```
class RangeWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (forms.TextInput(attrs=attrs.copy()), forms.TextInput(attrs=attrs.copy()))
        super(RangeWidget, self).__init__(widgets, attrs)
```

**Comment by carltongibson** [comment]
Hmmm. Yes. Bloody Reference Semantics. (Thanks for the PR)
