### ISSUE TITLE
MultipleChoiceFilter not working properly

### ISSUE THREAD

**Issue by topletal** [alex/django-filter#315]
When parsing url params with the same name (eg. ?name=john&name=mark), MultipleChoiceFilter is not working properly. The filter function already receive only the last value out of the list, so custom Filter doesn't help also. I think the problem might be where url arguments are received and passed into  filter function. For example when using something like:

 for n in self.request.query_params.get('name'):

the loop will loop only once, using the last value (as is in def filter). I found out that these multiple values of same name need to be parsed with getlist(): self.request.query_params.getlist('name').

**Comment by topletal** [comment]
upon further inspection, i found out that django-rest-framework was distributing only one (the last one) value. Apologies

**Comment by carltongibson** [comment]
No problem.

Can you explain what you mean about DRF? Maybe there's an issue we can look at there...

**Comment by topletal** [comment]
Well, the point is, that into MultipleChoiceFilter, into its filter function, the value incoming was just single value, the last value in the url. It seems that rest-framework or django itself takes the url arguments as form and runs it through clean. And cleaning only leaves the last value.
I fixed it this way: 

class MultipleValueFilter(Filter):
    def filter(self, qs, value):
        values = self.parent.data.getlist(self.name)   # <<--- here in parent, cleaned_data already had the only single value, however data was still full list value of all the url arguments with given name
        return self.custom_filter(qs, values)


class PageViewFilter(MultipleValueFilter): # here I create custom filter field for every url argument I need as need to filter very specific fields on each different url argument.
    def custom_filter(self, qs, values):
        for v in values:
            pq = MyModel.objects.filter(Q(modelfield__icontains=v) | Q(modelfield2__icontains=v)).values_list('parent_model_id', flat=True)
            qs = qs.filter(pk__in=pq)
        return qs

I'm not that skilled in django yet, so I don't know if this is the correct way.
