### ISSUE TITLE
Add a datetimefromtorangefilter

### ISSUE THREAD

**Issue by creynold** [alex/django-filter#329]
It would be nice to have a datetime range filter in addition to the date/time range filters.

**Comment by areski** [comment]
@creynold have you build a solution? I was looking for the same thing

**Comment by carltongibson** [comment]
OK. As @newfylox on #369 the [docs say `DateRangeField` already handles `DateTimes` too](http://django-filter.readthedocs.org/en/latest/ref/filters.html#datefromtorangefilter) — but it doesn't.

Looking at #215 — when the field was added — it doesn't seem `DateTime` compatibility is actually tested. 

Two options here: 

1. Add some tests and then compat and docs on usage for `DateTimes` to `DateRangeField`. 
2. Add a separate `DateTimeRangeField` (with docs and tests)

I'm happy for anyone to take that on. 

//cc. @bogdal

**Comment by rpkilby** [comment]
@carltongibson - I believe that the DateRangeField is intended to validate date ranges, which in turn can be used to filter date and datetime fields on the model. If you look at the [compress](https://github.com/alex/django-filter/blob/0.12.0/django_filters/fields.py#L41-L49) method, it converts the validated date range into datetimes that are inclusive of datetimes occuring on the end date.

**Comment by carltongibson** [comment]
@rpkilby Brilliant. Good link. 

This is a documentation issue. Since it's come up more than once, we need a couple of decent examples showing the filtering in action for **BOTH** Date and DateTime fields.

**Comment by rpkilby** [comment]
So to sum up:
- Clarify documentation for `DateRangeField`/`DateFromToRangeFilter`.
- Add tests for above documentation that demonstrate the datetime behavior.
- Add `DateTimeRangeField` & `DateTimeFromToRangeFilter` with tests and docs.

**Comment by bogdal** [comment]
@rpkilby You are absolutely right. Docs could be misleading. Right now I'm working on `DateTimeRangeField` and `DateTimeFromToRangeFilter`. Stay tuned.

**Comment by rpkilby** [comment]
@bogdal - sweet. 
Side note,  am still working on the CSV equivalent of these.

**Comment by carltongibson** [comment]
@rpkilby — I was hoping you'd say that. :-)

@bogdal — Awesome! Thanks.

**Comment by shredding** [comment]
Since the most form editors (in my case wagtail) do not allow adding a timezone, can we add something along the lines of:

```
if settings.USE_TZ and timezone.is_naive(value)
    default_timezone = timezone.get_default_timezone()
    value = timezone.make_aware(value, default_timezone)
```

Django will raise a warning if it's not in ...

**Comment by carltongibson** [comment]
@shredding Yep. Totally happy to see something there. [It might need to be a little more sophisticated...](https://docs.djangoproject.com/es/1.9/topics/i18n/timezones/#selecting-the-current-time-zone) — and then it might need to account for different setups... — but yep. PRs welcome.
