### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by snuderl** [alex/django-filter#330]
I was looking over the docs but couldn't find any mention of required fields. Is there are good way to indicate a filter field is required to be set?

**Comment by highpost** [comment]
Adding "required = True" works for me, but is undocumented. I was thinking of adding a doc pull request for this.

**Comment by snuderl** [comment]
Nice, thank you for this. :+1:

**Comment by saichander17** [comment]
```
class UserAnnotationFilterSet(django_filters.FilterSet):
    file = NumberInFilter(field_name="file_id", required=True)

```
I tried to do this, but it's not really imposing anything. Am I missing something here?

**Comment by angel-zeitoune** [comment]
The `required=True` parameter works correctly for a query of a list of records.
But unfortunately, when you want to get a record by id it is also required, it does not make sense.

**Comment by pmontu** [comment]
Filteres Button on DRF Browsable API disappears if required=True is set

**Comment by dontic** [comment]
> Filters Button on DRF Browsable API disappears if required=True is set

The filter button disappears during the 400 error if no filters are passed:
![image](https://github.com/carltongibson/django-filter/assets/25914304/2f3f5051-9c54-4a93-8cc4-1b3292c7c33f)


But it will appear again if you pass the required fields via the url first:
![image](https://github.com/carltongibson/django-filter/assets/25914304/65190f3a-4606-499a-ac0c-9acc0c878963)
