### ISSUE TITLE
Replace get_field_by_name() with use get_field() for Django 1.9+

### ISSUE THREAD

**Issue by unklphil** [alex/django-filter#334]
`django_filters/filterset.py:103: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'`

See: https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-from-the-old-api

This is obviously not a critical issue, as `get_field_by_name` will only be removed in Django 1.10

**Comment by carltongibson** [comment]
Already addressed in #331
