### ISSUE TITLE
Pagination documentation

### ISSUE THREAD

**Issue by techdragon** [alex/django-filter#339]
Does anyone have documentation on how to use this with django's built in pagination capabilities ? https://docs.djangoproject.com/en/dev/topics/pagination/

**Comment by carltongibson** [comment]
Pass the FilterSet's QuerySet to the pagination mechanism. (StackOverflow is your place for this kind of question.)

**Comment by techdragon** [comment]
@carltongibson - I've clarified my issue. I wasnt so much asking for help with fixing my problem as pointing out something that could be better documented in the project documentation.

**Comment by BigChief45** [comment]
@techdragon Did you find a way to do this? With Class based views.

**Comment by rpkilby** [comment]
Does pagination not automatically work with the `FilterView`? It ultimately inherits `MultipleObjectMixin`, which is the class that provides pagination behavior.

**Comment by BigChief45** [comment]
@rpkilby Yes I realized that after, checking the source. I think this would be something good to add to the docs.
