### ISSUE TITLE
Abstract base FilterSet classes?

### ISSUE THREAD

**Issue by leifurhauks** [alex/django-filter#340]
Is it possible to create abstract base FilterSet classes? By that I mean something similar to django's abstract base models; a way of defining a filter on a class that FilterSets bound to different models can inherit.

e.g.:
```python
class MyBaseFilterSet(FilterSet):
    id = NumberFilter(name='id')

    class Meta:
        abstract = True
        fields = ['id']
```

I guess the tricky part would be merging the `fields` meta option of the concrete class with those of its abstract parent(s).

**Comment by carltongibson** [comment]
Why would they need to be abstract? Just subclass. (Does that not work?)

Yes. You need to redeclare the metaclass. But that's OK. (Any typing saved would more than lost in trying to solve weird bugs.)

**Comment by leifurhauks** [comment]
> You need to redeclare the metaclass

Do you mean re-declare the Meta in the child class, or declare the parent/base class with `metaclass=FilterSetMetaclass`?

**Comment by carltongibson** [comment]
>  re-declare the Meta in the child class

That one.

**Comment by leifurhauks** [comment]
Okay, so to adjust the example I gave above, it should look like the following, correct?
```python
class MyBaseFilterSet(FilterSet):
    id = NumberFilter(name='id')
```
then:
```python
class MyConcreteFilterSet(MyBaseFilterSet):
    class Meta:
        model = MyModel
        fields = ['id']
```

**Comment by carltongibson** [comment]
... and does that not work?
