### ISSUE TITLE
Multiple filters in one view with the same Attributes (how to scope filters)?

### ISSUE THREAD

**Issue by gabn88** [alex/django-filter#341]
First, thank you for this nice django plugin.

I have a view in which I have to filter multiple different Django models, say Model A and Model B.

Model A has an attribute 'name', and Model B also has an attribute 'name'. I created two filtersets:

class ModelAFilter(django_filters.FilterSet):
    ''' This filter is used in the views '''
    class Meta:
        model = ModelA
        fields = {'name': ['icontains'], # with icontains you dont need exact
                  'id': ['exact'],
                  }

class ModelBFilter(django_filters.FilterSet):
    ''' This filter is used in the views '''
    class Meta:
        model = ModelB
        fields = {'name': ['icontains'], # with icontains you dont need exact
                  'id': ['exact'],
                  }

As expected, when I filter model A on name Something, it also filters model B on name Something, as the query becomes: 
?name__icontains=Something

Is it possible to scope the filters somehow to say: modela_name_icontains=Something?

**Comment by GraphGrail** [comment]
Hi @gabn88 , i have axactly same problem, but in reverse! Could you help to merge two models into one filter with the same fieldnames?  Here details:  http://stackoverflow.com/questions/34386459/django-filter-merge-2-models-in-one-filter

I would like to know how do you able to filter 2 models? how do you pass 2 querysets?

**Comment by rpkilby** [comment]
Hi @gabn88. It isn't documented, but the FilterSet class accepts a [`prefix`](https://github.com/alex/django-filter/blob/0.12.0/django_filters/filterset.py#L286) which is in turn passed to the underlying [form](https://github.com/alex/django-filter/blob/0.12.0/django_filters/filterset.py#L372-L386). I believe this would solve your problem.

**Comment by carltongibson** [comment]
I'm going to close this. I don't think there's an actionable issue here. Feel free to shout if I'm missing something.

**Comment by gabn88** [comment]
@rpkilby Thank you, did this indeed solve my issue!

**Comment by valentijnscholten** [comment]
Would be nice to see it documented
