### ISSUE TITLE
Could you issue a release to PyPI?

### ISSUE THREAD

**Issue by aaugustin** [alex/django-filter#345]
https://github.com/alex/django-filter/commit/7df668c6eddad0202feca3659ef41378b47c5bd8#diff-c82ea95d2a317d98860bf154f27d3e17L74 fixes a loud deprecation warning on Django 1.9.

It would be nice to push a release to PyPI with this change.

Thanks!

**Comment by carltongibson** [comment]
Coming w/b 4th Jan

**Comment by gustavi** [comment]
Some news ?

**Comment by carltongibson** [comment]
w/b means week beginning. That's this week.

**Comment by carltongibson** [comment]
Here you go: https://github.com/alex/django-filter/releases/tag/0.12.0 — On PyPI now.

**Comment by aaugustin** [comment]
Thanks Carlton!
