### ISSUE TITLE
filtering a view when using get/post in class

### ISSUE THREAD

**Issue by whoisearth** [alex/django-filter#346]
I'm not finding it in the documentation but curious how to do a filter based.

Simply put I have the following class-based view - 

    class WidgetList(generics.ListCreateAPIView):
        queryset = Widget.objects.all()
        serializer_class = WidgetSerializer
        filter_class = WidgetFilter

        def get(self, request):
            if request.user:
                queryset = self.get_queryset().filter(owner=request.user)
                for object in queryset:
                    object.code = decrypt_code(masterkey,
                                                       userkey,
                                                       object.code)
            else:
                queryset = self.get_queryset()

            page = self.paginate_queryset(queryset)
            if page is not None:
                serializer = self.get_serializer(page, many=True)
                return self.get_paginated_response(serializer.data)

            serializer = WidgetSerializer(queryset, many=True)
            return Response(serializer.data)

The problem is when I try to do a filter it doesn't recognize anything aside from the filter(owner=request.owner) which is being defaulted.

**Comment by rpkilby** [comment]
Hi @whoisearth - this isn't really an issue with django-filter, and more in how you've overridden the DRF base class. If you follow the method calls, you'll see that the `filter_class` isn't called anywhere, which is why none of your filtering is working.

It looks like you're just trying to override the behavior of the queryset, so it would make sense to override `get_queryset()`.

something like...
```py
class WidgetList(generics.ListCreateAPIView):
    queryset = Widget.objects.all()
    serializer_class = WidgetSerializer
    filter_class = WidgetFilter

    def get_queryset(self):
        queryset = super(WidgetList, self).get_queryset()

        if self.request.user:
            queryset = queryset.filter(owner=self.request.user)
            for object in queryset:
                object.code = decrypt_code(masterkey, userkey, object.code)

        return queryset
```

@carltongibson - I think this is safe to close?
