### ISSUE TITLE
How to contribute to i18n translation?

### ISSUE THREAD

**Issue by kxxoling** [alex/django-filter#358]
I found there's some gettext files, and like to contribute to Chinese translation but did not figure out how to generate locale files.

**Comment by carltongibson** [comment]
Oooh. Good question. 

> `X-Generator: Poedit 1.5.4`

What's `Poedit`?

**Comment by kxxoling** [comment]
@carltongibson Sorry, I'm not sure what do you mean. I do not need a ``.po`` editor, but wonder how to generate ``zh_CN/*/*.po`` files. As it's not a django project, so I cannot use ``./manage.py makemessages`` here.

BTW, I think ``.mo`` files should not be a part of this project as they are only compiled ``.po`` files.

**Comment by carltongibson** [comment]
Use django-admin.py as per the examples usage https://docs.djangoproject.com/es/1.9/ref/django-admin/#django-admin-makemessages

**Comment by kxxoling** [comment]
Translation finished! Shall I add the .mo file into git commit?

PR created here: https://github.com/alex/django-filter/pull/359

**Comment by kxxoling** [comment]
As an promt to anybody who want to contribute to translation later, you could run ``django-admin makemessages --locale YOUR_LANGUAGE`` in ``~repo/django_filters/`` directory to generate ``.po`` files and run ``django-admin compilemessages --locale zh_CN`` compile ``.po`` files to ``.mo``.

**Comment by carltongibson** [comment]
@kxxoling Great work. 

Do you fancy adding that How To note to the docs? http://django-crispy-forms.readthedocs.org/en/latest/contributing.html

**Comment by kxxoling** [comment]
Not sure what else should I do. Add the HOW TO I wrote to django-crispy-forms?
