### ISSUE TITLE
AllValuesFilter does not have an empty value

### ISSUE THREAD

**Issue by bitrut** [alex/django-filter#36]
When I use AllValuesFilter, I can't choose value that does not affect (filter) result list. I can only choose one of the model objects.

This is how I resolved this issue:

    def __init__(self, *args, **kwargs):
        super(ApplicationFilter, self).__init__(*args, **kwargs)
        self.filters['a_filter_field'].field.choices.insert(0, ('', u'---------'))

**Comment by 57even** [comment]
+1

**Comment by carltongibson** [comment]
Closing this in favour of #261
