### ISSUE TITLE
Support true and false for boolean fields

### ISSUE THREAD

**Issue by imaia** [alex/django-filter#360]
I just saw that a boolean field will only filter property if its parameter is True or False. "true", "false" are not parsed properly. That seems like something to improve to me, as in the HTML layer, true and false are much more common and natural for parameters, so I suggest that the boolean filter to accept true, True, false and False notation.

**Comment by rpkilby** [comment]
Hi @imaia - this was implemented in #270, however it's not the default widget for `BooleanFilter`s. This can be overridden though with the widget param in the constructor.

**Comment by carltongibson** [comment]
Spot on.
