### ISSUE TITLE
MultipleCharFilter for undefined MultipleChoice and in lookup_type

### ISSUE THREAD

**Issue by steel971** [alex/django-filter#377]
The behavior is close to `MultipleChoiceFilter`, but instead of a ChoiceList or a Query, make it with a simple string.
(eg `?cities=los-angeles&cities=san-francisco`).
Here the code I use in order to have this done without `django-filter` :
<pre>
cities = []
        cities.extend(request.GET.getlist('cities[]', []))
        if cities:
            self.queryset = self.queryset.filter(city__slug__in=cities)
</pre>

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests if you want to add it.
