### ISSUE TITLE
Add "Any" filter to ChoicesField

### ISSUE THREAD

**Issue by cvk77** [alex/django-filter#45]
The ChoicesField currently doesn't provide an "Any" or "Unknown" filter entry, so as soon as a ChoiceField is added to a search form, the user has to always select an entry.

I currently workaround this by adding an empty filter in the Filter's constructor, but it would be great if there could be an easier way to achieve this:

    class NicerFilterSet(django_filters.FilterSet):

    def __init__(self, *args, **kwargs):
        super(NicerFilterSet, self).__init__(*args, **kwargs)

        for name, field in self.filters.iteritems():
            if isinstance(field, ChoiceFilter):
                # Add "Any" entry to choice fields.
                field.extra['choices'] = tuple([("", "Any"), ] + list(field.extra['choices']))`

**Comment by carltongibson** [comment]
Closing this in favour of #261

**Comment by paulhauner** [comment]
Here's a Python3 compatible version of the original work-around by @cvk77 (see top of thread)

```
class NicerFilterSet(django_filters.FilterSet):

def __init__(self, *args, **kwargs):
  super(NicerFilterSet, self).__init__(*args, **kwargs)

  for name, field in self.filters.items():
    if isinstance(field, ChoiceFilter):
      # Add "Any" entry to choice fields.
      field.extra['choices'] = tuple([("", "Any"), ] + list(field.extra['choices']))
``` 

Changes:
`self.filters.iteritems()` was changed to `self.filters.items()`
