### ISSUE TITLE
MultipleChoiceFilter does not use lookup_type

### ISSUE THREAD

**Issue by lexotron** [alex/django-filter#49]
MultipleChoiceFilter.filter() should be updated to include something along these lines:

    def filter(self, qs, value):
        (...)
        lookup = self.lookup_type or 'exact'
        for v in value:
            q |= Q(**{'%s__%s' % (self.name, self.lookup_type): v})
        (...)

I haven't really taken a good look at any of the code, so this is just my initial solution.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.

**Comment by rixx** [comment]
Is your offer still open? Adding ``lookup_expr`` to MultipleChoiceFilter should be a very short PR (think one or two lines, plus tests), and might be useful to more people. I just added it to my project by overriding ``get_filter_predicate`` as the class docs suggest, but it took me a while to figure out that I should do this.

**Comment by carltongibson** [comment]
Hey @rixx! Yep. Very happy to look at a PR here. (Thanks! 🤹‍♂️)
