### ISSUE TITLE
LinkWidget doesn't not work correctly with other filters

### ISSUE THREAD

**Issue by lucianolev** [alex/django-filter#92]
Hi
I was using this app for my project and I found some issues with the LinkWidget.
As the widget is implemented with a set of links, they don't integrate well when combined with other filters. This is because the href attr of the links in the widget just append a value to the GET request, instead of submitting the HTML form element of the Filterset.
This also brings other issues such as not having a way to change the destination url of the filter after submit (The use case is when you need to show the same filter in multiple views).

The only way I found to get around this is to implement the widget as a hidden input that submits the chosen option together with the form through JS. It's not so clean, but is the cleanest way I found.

Thanks

**Comment by carltongibson** [comment]
The LinkWidget is great for generating a list of links for different groups of objects, e.g. Issues{All, Open, Closed}. 

No doubt there are more complicated use-cases than this, but I'm going to close this issue as there's nothing actionable here.
